[package]
name = "variant"
version = "0.1.0"
authors = ["Austin Jones <austin.jones@aetion.com>"]
edition = "2018"

[dependencies]
rand = "0.7.0"
rand_xoshiro = "0.3.0"
array_ext = "0.2.0"

[[bin]]
name = "example"
path = "examples/example.rs"
